version: '3'

services:
  app:
    build: .
    command: pipenv run python manage.py run
    working_dir: /app
    depends_on:
      - database
    ports:
      - 5000:5000
    networks:
      - gamersclub
    volumes:
      - .:/app
      - virtualenvs:/root/.local/share/virtualenvs

  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: gamersclub
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432
    networks:
      - gamersclub
    volumes:
      - database:/var/lib/postgresql/data

networks:
  gamersclub:
    external: true

volumes:
  virtualenvs:
  database:
